language: java
jdk: oraclejdk8

before_install:
  - sudo echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod/ trusty main" > azure.list
  - sudo cp ./azure.list /etc/apt/sources.list.d/
  - apt-key adv --keyserver packages.microsoft.com --recv-keys EB3E94ADBE1229CF
  - sudo apt-get update
  - sudo apt-get install azcopy

install: true
cache:
  directories:
  - $HOME/.m2

script:
  - mvn clean install
  - azcopy --source /home/travis/build/prashanthmadi/awesome_storm/target/awesome_storm-1.0-SNAPSHOT.jar --destination https://stormprmadi.blob.core.windows.net/stormprmadi-2018-09-02t02-27-34-568z/awesome_storm-1.0-SNAPSHOT.jar --dest-key $AZURE_STORAGE_ACCESS_KEY
