language: java
jdk: oraclejdk8

before_install:
  - wget -O azcopy.tar.gz https://aka.ms/downloadazcopylinux64
  - tar -xf azcopy.tar.gz
  - sudo ./install.sh
  - sudo apt-get install libunwind8

install: true
cache:
  directories:
  - $HOME/.m2

script:
  - mvn clean install
  - azcopy --quiet --source /home/travis/build/prashanthmadi/awesome_storm/target/awesome_storm-1.0-SNAPSHOT.jar --destination https://stormprmadi.blob.core.windows.net/stormprmadi-2018-09-02t02-27-34-568z/awesome_storm-1.0-SNAPSHOT.jar --dest-key $AZURE_STORAGE_ACCESS_KEY
